### ISSUE TITLE
레이아웃 변경 

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#100]
![image](https://user-images.githubusercontent.com/51853700/142573346-41e4ab85-af08-48c8-a6f4-ba36785cbc8a.png)

![image](https://user-images.githubusercontent.com/51853700/142572805-62b70257-94c5-4e02-a00a-102259a4c62a.png)

**Comment by Jay-JYKim91** [comment]
데이터 팝업으로 보낼 때 carPrice 조정필요
예약 폼 팝업창 다시 보기
