### ISSUE TITLE
디테일 피드백 사항

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#102]
### 1. 한 줄에서 아무곳이나 클릭하면 상세페이지로 -> 마스터에서도 변경
![image](https://user-images.githubusercontent.com/51853700/142393156-918f9b4f-e0a6-408a-a6d8-0d69cb22951e.png)

### - 이렇게 오른쪽에 띄워주기
![image](https://user-images.githubusercontent.com/51853700/142396073-3a2807af-fdad-4793-b40e-7eb0058a5ceb.png)

### 5. 한도도 가능해야함은 2에만 들어가야 합니다. 1도 현재 들어가있어요. 2는 들어갔는지 아닌지 확인못했습니다
  * 신용
  0 = 증빙 필요x
  1 = [신용카드or소득3개월증빙or보증금30%]
  2 = [본인신용카드(한도도가능해야함)or 보증금30%이상
### 8. 방문 / 배차신청 select 넣기 -> admin 전달 
* 배차비표 보기 버튼 누르면 새창띄워서 보여주기 or 배차신청 선택하면 배차비표 보여주기
### 12. 차량사진 차량별 디폴트 사진 넣기

**Comment by sne12345** [comment]
1. 한 줄에서 아무곳이나 클릭하면 상세페이지로 -> 마스터에서도 변경

3. 월렌트 실시간 상세페이지에서 간편상담신청 버튼 띄우기
- 이렇게 오른쪽에 띄워주기

8. 방문 / 배차신청 select 넣기 -> admin 전달
배차비표 보기 버튼 누르면 새창띄워서 보여주기 or 배차신청 선택하면 배차비표 보여주기
10. 대기신청문자에 계좌번호 써주기
11. 확정문자에 운전면허증 보내달라는내용 쓰기
12. 차량사진 차량별 디폴트 사진 넣기(보류)
13. 상세페이지 아래부분 디자인 수정

**Comment by Jay-JYKim91** [comment]
3. 배차 신청 관련 value는 'pickupPlace'라는 이름으로 admin으로 보냄

**Comment by sne12345** [comment]
(완료)
4. 대기신청문자에 계좌번호 써주기
5. 확정문자에 운전면허증 보내달라는내용 쓰기
7. 상세페이지 아래부분 디자인 수정

(미완)
1. 한 줄에서 아무곳이나 클릭하면 상세페이지로 -> 마스터에서도 변경
2. 월렌트 실시간 상세페이지에서 간편상담신청 버튼 띄우기
3. 방문 / 배차신청 select 넣기 -> admin 전달
배차비표 보기 버튼 누르면 새창띄워서 보여주기 or 배차신청 선택하면 배차비표 보여주기
6. 차량사진 차량별 디폴트 사진 넣기

**Comment by sne12345** [comment]
(완료)
14. 프로세스 직원들에게 고지하고 배포하기
15. 문자 수신인 추가하기
11. 예약 신청하기에 계약 기간 기입
10. 견적서에 자차보험 - 가입[한도有]
8. 견적서에 VAT 미포함으로
7. 디폴트 사진인거는  아래에 * 실제 차량 사진과 차이가 있을 수 있습니다. 라고 안내문 쓰기
-> 리스트 길이가 1일 때 디폴트 사진임
3. 배차비표 보기 버튼 누르면 새창띄워서 보여주기 or 배차신청 선택하면 배차비표 보여주기
![image](https://user-images.githubusercontent.com/51853700/143526075-d3a61ef7-8cbd-4bee-9296-638acbf19ffa.png)
10. 만 21세 이상 ~ 만 26세 미만 / 만 26세 이상
2. 월렌트 실시간 상세페이지에서 간편상담신청 버튼 띄우기
3. 방문 / 배차신청 select 넣기 -> admin 전달 -> 모렌으로 전달할 때 data에 넣음(carPrice라는 이름으로)
4. 대기신청문자에 계좌번호 써주기
5. 확정문자에 운전면허증 보내달라는내용 쓰기
7. 상세페이지 아래부분 디자인 수정
1. 한 줄에서 아무곳이나 클릭하면 상세페이지로 -> 마스터에서도 변경
11. 예약금 빨간색 / 월대여료 파란색
12. 실시간 예약에서 [공급가] -> [월대여료(VAT미포함)]
13. 실시간 예약에서  
 약정 주행거리 선택에 따라 대여료가 달라집니다. -> 렌트 기간, 약정 주행거리, 연령 선택에 따라 대여료가 달라집니다.
7. 사진 크기 수정
9. 차량 픽업 방법이 배차받을주소 위에 올라가게 +  배차 신청을 선택할 경우에 배차받을 주소가 나오도록
