### ISSUE TITLE
디테일 피드백

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#124]
* 실시간 예약 -> 캠핑카 예약현황 캘린더
* 모바일 캘린더에서 들어가면 첫날 동그라미 표시해주기

**Comment by sne12345** [comment]
캘린더 모바일
* 날짜를 선택하시면 아래에 해당 날짜에 예약가능한 캠핑카가 뜹니다.

캘린더 PC & 모바일
* ↓

**Comment by sne12345** [comment]
예약 상세 페이지 - 가격표

**Comment by Jay-JYKim91** [comment]
admin setting menu 버튼 크게 만들어세 상단에 놓기

**Comment by sne12345** [comment]
* 모바일에서 1/1, 0/1이 헷갈린다고함 -> 색깔별로 무슨뜻인지 쓰기
* 메뉴가 헷갈린다고함 -> ?

**Comment by Jay-JYKim91** [comment]
![KakaoTalk_Photo_2021-12-29-16-44-12](https://user-images.githubusercontent.com/69047256/147638824-94908418-cc7f-4709-b992-e1f7ee3a4028.jpeg)
