### ISSUE TITLE
관리자 페이지 조건별조회 & 검색

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#135]

**Comment by sne12345** [comment]
ElasticSearch

**Comment by Jay-JYKim91** [comment]
admin/상담신청내역 -> 유형 별로 나누기

**Comment by sne12345** [comment]
# 상담신청 유형별 @GetMapping("/admin/counsel/title/{title}")

**Comment by sne12345** [comment]
* 간편상담신청, 
* 한눈에상담신청, 
* 월렌트실시간, 
* 실시간견적내기, 
* 누구나장기렌트, 
* 누구나차량상세, 
* 캠핑카렌트
