### ISSUE TITLE
팝업창 html/css로 작업하기(데이터 db에서 받기)

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#140]

**Comment by sne12345** [comment]
<div>
    <h1>파일 업로드</h1> <hr>

    <form th:action="@{/admin/test/image}" method="post" enctype="multipart/form-data">
        제목 : <input type="text" name="title"> <br>
        파일 : <input type="file" name="file"> <br>
        <button>등록하기</button>
    </form>
</div>

**Comment by sne12345** [comment]
# 값 업로드

# Get
@GetMapping("/admin/value/{title}")
- return "value"

# Post
@PostMapping("/admin/value")
- private String title;
- private String value;

**Comment by Jay-JYKim91** [comment]
S3 파일 업로드 ajax 방식 찾아서 적용하기

**Comment by Jay-JYKim91** [comment]
캠핑카 내용 팝업은 기본 정보 수정에서 수정할 수 있도록

**Comment by Jay-JYKim91** [comment]
admin 메뉴 변경
- 기존: 기본 내용 설정
- 변경 후: 캠핑카 내용 수정
- 파일명 변경은 아직

**Comment by Jay-JYKim91** [comment]
팝업4(모바일 버전 캠핑카 내용) 디자인 적용 클래스
![KakaoTalk_Photo_2022-01-20-17-05-03 002](https://user-images.githubusercontent.com/69047256/150297898-6c5cf69f-4a0a-4745-ba78-f222f2e1c336.jpeg)

**Comment by Jay-JYKim91** [comment]
어드민에서 팝업 4 내용 수정할 때 쓸 title
![KakaoTalk_Photo_2022-01-20-17-05-02 001](https://user-images.githubusercontent.com/69047256/150298022-9c29596f-991f-4edd-a2bc-935f93d40988.jpeg)

**Comment by Jay-JYKim91** [comment]
어드민에서 팝업 4 내용 수정할 때 쓸 title - 수정
![KakaoTalk_Photo_2022-01-21-17-31-37](https://user-images.githubusercontent.com/69047256/150493339-f9181840-1e79-43f4-a4af-345a3bf07ee5.jpeg)

**Comment by sne12345** [comment]
# CampingCarPrice 추가 데이터
    private String fuel;
    private String gearBox;
    private String license;
    private String personnel;

**Comment by sne12345** [comment]
# @PostMapping("/admin/campingcar/setting")

{"campingCarList":[{"carName":"europe","carNum":"70호4097",...}],
 "campingCarCommonValue":{"camper_price":"....", "rent_policy":"....", ...}}



# campingCarList
    private String carName;
    private String carNum;
    private String carCode;
    private String season;
    private String deposit;
    private String yearmodel;
    private String fuel;
    private String gearBox;
    private String license;
    private String personnel;


# campingCarCommonValue

    private String camper_price;
    private String rent_policy;
    private String rent_insurance;
    private String rent_rule;
    private String refund_policy;
    private String driver_license;

**Comment by sne12345** [comment]
# @GetMapping(value = "/admin/campingcar/setting/menu")

### return  "campingCarList"

# List<CampingCarPrice> campingCarList -> 리스트라서 하나씩 꺼내야 함 


    @Id
    @Column(name = "car_name")
    private String carName;

    @Column(columnDefinition = "LONGTEXT")
    private String basic_option;

    @Column(columnDefinition = "LONGTEXT")
    private String facility;

    private String carNum;
    private String carCode;
    private String yearmodel;
    private String fuel;
    private String gearBox;
    private String license;
    private String personnel;
    private String camper_price;
    private String rent_policy;
    private String rent_insurance;
    private String rent_rule;
    private String refund_policy;
    private String driver_license;

**Comment by sne12345** [comment]
# 캠핑카 내용 수정 추가내용

private String carNum;
private String yearmodel;

# 생각필요

private String carCode;

# 캠핑카 등록하는거 만들어 보기
