### ISSUE TITLE
리뷰쓰기-캠핑카,렌트카(고민하기)

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#152]

**Comment by Jay-JYKim91** [comment]
![KakaoTalk_Photo_2022-02-15-17-47-57](https://user-images.githubusercontent.com/69047256/154025779-0c7ec762-8006-45e0-bffd-ee7a175e0444.jpeg)

**Comment by sne12345** [comment]
# POST /camping/calendar/review
#### 보내는 데이터

    private String carName;
    private String text;

    private List<MultipartFile> imageList;
    private MultipartFile video;
    private String password;

**Comment by Jay-JYKim91** [comment]
![KakaoTalk_Photo_2022-02-16-17-40-04](https://user-images.githubusercontent.com/69047256/154227082-4a00f4b5-b5d4-43d3-96cb-791283a07d7a.png)
![KakaoTalk_Photo_2022-02-16-17-39-57](https://user-images.githubusercontent.com/69047256/154227098-cf1392a6-756c-4d2e-86ea-842e29320cf0.png)
