### ISSUE TITLE
관리자페이지-가격표 수정하는기능만들기

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#154]

**Comment by sne12345** [comment]
# @GetMapping("/admin/rentcar/price/menu") -> admin/rentcar_price_menu

        List<MonthlyRent> monthlyRentList
        List<YearlyRent> yearlyRentList 
        List<TwoYearlyRent> twoYearlyRentList

# MonthlyRent
    private  Long id;

    private String category1; // 국산, 외제차의 분류
    private String category2; // 중형차, 경차 등 큰 분류

    @Column(unique = true)
    private String name;

    private String deposit;
    private String cost_for_2k;
    private String cost_for_2_5k;
    private String cost_for_3k;
    private String cost_for_4k;
    private String cost_for_others;
    private String age_limit;
    private String cost_per_km;

    private String nameMoren;
    private Long start;
    private Long end;

    private String credit;
    private String img_url;

# YearlyRent

    private  Long id;

    private String category1; // 국산, 외제차의 분류
    private String category2; // 중형차, 경차 등 큰 분류
    private String deposit;
    private String name;
    private String cost_for_20k;
    private String cost_for_30k;
    private String cost_for_40k;
    private String cost_for_others;
    private String age_limit;
    private String cost_per_km;

    private String nameMoren;
    private Long start;
    private Long end;

    private String credit;
    private String img_url;


# TwoYearlyRent

    private  Long id;

    private String category1; // 국산, 외제차의 분류
    private String category2; // 중형차, 경차 등 큰 분류
    private String deposit;
    private String name;
    private String cost_for_20Tk;
    private String cost_for_30Tk;
    private String cost_for_40Tk;
    private String cost_for_others;
    private String age_limit;
    private String cost_per_km;

    private String nameMoren;
    private Long start;
    private Long end;

    private String credit;
    private String img_url;

**Comment by sne12345** [comment]
# @PutMapping("/admin/rentcar/price/monthly/{monthlyId}")

#### 보내는 데이터

    private String category1; // 국산, 외제차의 분류
    private String category2; // 중형차, 경차 등 큰 분류
    private String name;

    private String deposit;
    private String cost_for_2k;
    private String cost_for_2_5k;
    private String cost_for_3k;
    private String cost_for_4k;
    private String cost_for_others;
    private String age_limit;
    private String cost_per_km;

    private String nameMoren;
    private Long start;
    private Long end;

    private String credit;
    private String img_url;

#### 받는 데이터

    result -> 1 or 0

**Comment by sne12345** [comment]
# 이미지 MultiPart로 보낼 때
#### @PutMapping("/admin/rentcar/price/monthly/image/{monthlyId}")
#### 보내는 데이터

    private String category1; // 국산, 외제차의 분류
    private String category2; // 중형차, 경차 등 큰 분류
    private String name;

    private String deposit;
    private Float cost_for_2k;
    private Float cost_for_2_5k;
    private Float cost_for_3k;
    private Float cost_for_4k;
    private String cost_for_others;
    private String age_limit;
    private String cost_per_km;

    private String nameMoren;
    private Long start;
    private Long end;

    private String credit;
    private String img_url;

    private MultipartFile file;


#### 받는 데이터

    result -> 1 or 0

**Comment by sne12345** [comment]
# 이미지 url로 보낼 때 - yearlyRent
#### @PutMapping("/admin/rentcar/price/yearly/{yearlyId}")

#### 보내는 데이터

    private String category1; // 국산, 외제차의 분류
    private String category2; // 중형차, 경차 등 큰 분류
    private String deposit;
    private String name;
    private Float cost_for_20k;
    private Float cost_for_30k;
    private Float cost_for_40k;
    private String cost_for_others;
    private String age_limit;
    private String cost_per_km;

    private String nameMoren;
    private Long start;
    private Long end;

    private String credit;
    private String img_url;

#### 받는 데이터

    result -> 1 or 0

**Comment by sne12345** [comment]
# 이미지 url로 보낼 때 - twoYearlyRent
#### @PutMapping("/admin/rentcar/price/twoYearly/{twoYearlyId}")

#### 보내는 데이터

    private String category1; // 국산, 외제차의 분류
    private String category2; // 중형차, 경차 등 큰 분류
    private String deposit;
    private String name;
    private Float cost_for_20Tk;
    private Float cost_for_30Tk;
    private Float cost_for_40Tk;
    private String cost_for_others;
    private String age_limit;
    private String cost_per_km;

    private String nameMoren;
    private Long start;
    private Long end;

    private String credit;
    private String img_url;

#### 받는 데이터

    result -> 1 or 0

**Comment by sne12345** [comment]
# 가격 새로 등록하기
#### @PostMapping(value="/admin/rentcar/price")
#### 보내는 데이터 

    // 공통
    private String category1; // 국산, 외제차의 분류
    private String category2; // 중형차, 경차 등 큰 분류
    private String name;

    private String cost_for_others;
    private String age_limit;

    private String nameMoren;
    private Long start;
    private Long end;

    private MultipartFile file;
    private int isTwoYearExist;  // 1이면 24개월 有, 2이면 24개월 無

    // 다른것
    private String deposit_monthly;
    private String deposit_yearly;
    private String deposit_twoYearly;

    private String cost_per_km_monthly;
    private String cost_per_km_yearly;
    private String cost_per_km_twoYearly;

    private String credit_monthly;
    private String credit_yearly;
    private String credit_twoYearly;

    // monthly
    private Float cost_for_2k;
    private Float cost_for_2_5k;
    private Float cost_for_3k;
    private Float cost_for_4k;

    // yearly
    private Float cost_for_20k;
    private Float cost_for_30k;
    private Float cost_for_40k;

    // twoYearly
    private Float cost_for_20Tk;
    private Float cost_for_30Tk;
    private Float cost_for_40Tk;


#### 받는 데이터

    -> result -> 1

**Comment by sne12345** [comment]
# 가격 삭제하기
#### @DeleteMapping("/admin/rentcar/price/{monthlyId}")
#### 받는 데이터

    -> result -> 1

**Comment by Jay-JYKim91** [comment]
퍼센트 치면 바로 가격 나오게

**Comment by sne12345** [comment]
# 월렌트 컬럼별로 수정
### @PutMapping("/admin/rentcar/price/monthly/{column}/{value}")

### column -> 보증금, 2500km, 3000km, 4000km, 21세
### value -> double type
