### ISSUE TITLE
장기렌트 쇼핑몰 만들기 - 관리자페이지에서 등록

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#159]
* 이미지 서버

**Comment by sne12345** [comment]
xm3 LE
48개월
총약정주행거리10만키로
512000원(vat포함)
보증금 200만원
순회정비 10회(구글 저신용종합참조-마켓팅폴더)


셀토스 트랜디2wd + 컨비니언스
xm3 LE
48개월
총약정주행거리10만키로
521000원(vat포함)
보증금 200만원
순회정비 10회(구글 저신용종합참조-마켓팅폴더)

**Comment by sne12345** [comment]
![Uploading 1C0A8575-60CF-4956-B669-EED41926C248.png…]()

**Comment by sne12345** [comment]
![7DF023CA-C9E7-4A0D-8B1E-C05AB5A22AB3](https://user-images.githubusercontent.com/51853700/157231255-79152cb1-f973-433e-beef-c9cccbc9e10e.png)

**Comment by Jay-JYKim91** [comment]
Main 디자인
https://www.autoplus.co.kr/smartbuy/WUSB040002.rb 
![리본카 - 중고차, 시스템으로 바로잡다](https://user-images.githubusercontent.com/69047256/157595342-3303af40-8572-402a-916b-f2450d7af25e.png)

**Comment by Jay-JYKim91** [comment]
Detail 디자인
https://www.lotterentacar.net/hp/kor/usedCar/longTerm/usedCarOneDetail.do?equnr=000000000010627039&reqer=1000016587
![롯데렌터카](https://user-images.githubusercontent.com/69047256/157596124-2f364412-b7a0-4a6a-8bf6-7b535d1c9e3a.png)
![스크린샷 2022-03-10 오후 2 31 47](https://user-images.githubusercontent.com/69047256/157596139-5780bf79-779f-4d41-a8f1-8529e8598783.png)

**Comment by sne12345** [comment]
# longTermRentList

    private String carNum;
    private String carColor;
    private String carYearModel;
    private String contractPeriod;
    private String contractKm;
    private String contractPrice;
    private String contractDeposit;
    private String contractMaintenance;
    private String newOld;

**Comment by sne12345** [comment]
# @GetMapping("/rent/long_term")

#### 받는 데이터
    List<LongTermRent> longTermRentList
    List<List<LongTermRentImage>> imageList


# @GetMapping("/rent/long_term/{longTermRentId}")

#### 받는 데이터
    LongTermRent longTermRent

**Comment by sne12345** [comment]
# 피드백 사항
* 사이트 초기화면 누구나장기렌트칸에 '상품보기' 만들고. 온라인상담신청대신해도 되고
* 순회정비 내역해서 누구나상품처럼 이쁘게 만들고~
* 누구나 상품 바로 밑에 상담신청 만드시고
* 48개월 -에서 - 는 빼던가 색상이면  있는거다써준던가

**Comment by sne12345** [comment]
![image](https://user-images.githubusercontent.com/51853700/157800398-83f2db1e-845e-4b9c-a602-0c5b126a8b4c.png)
누구나장기렌트
4년장기렌트 신차중고차 전국최저가상품 바로가기

**Comment by sne12345** [comment]
# 피드백 
* 썸네일에 신차장기/중고차장기 띠 두르기
* 10만키로 -> 총약정km : 10만km
