### ISSUE TITLE
europe_reserve 스마트스토어처럼

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#210]

**Comment by sne12345** [comment]
![쏠라티-0](https://user-images.githubusercontent.com/51853700/153345087-748bc5bf-f86a-47b6-bda8-18176fc3f899.png)
![쏠라티-1](https://user-images.githubusercontent.com/51853700/153345089-9c667917-d98d-438f-896d-642d522f5515.png)
![쏠라티-2](https://user-images.githubusercontent.com/51853700/153345091-d17db6c1-4b94-462a-bdaa-1885f56a35eb.png)
![쏠라티-3-사진](https://user-images.githubusercontent.com/51853700/153345095-dea649f4-a32b-4b59-bbfe-65b6833a508c.png)
![쏠라티-4-옵션](https://user-images.githubusercontent.com/51853700/153345100-0296f871-b519-43f0-a844-8031f30a20e5.png)
![쏠라티-5-캠핑용품](https://user-images.githubusercontent.com/51853700/153345101-5bfadb61-a364-4789-b3c7-8e8d5ae06b41.png)
![쏠라티-6-서비스박스](https://user-images.githubusercontent.com/51853700/153345102-b89c676c-ecb4-4ff2-aa4f-5b402ca79316.png)
![쏠라티-7-도면](https://user-images.githubusercontent.com/51853700/153345104-257e756b-48f6-4c28-8704-3753edb00d87.png)
![쏠라티-8-후기이벤트](https://user-images.githubusercontent.com/51853700/153345106-91a44205-b7ad-4134-82f7-607d8cd6d9e2.png)
![쏠라티-9-차고지](https://user-images.githubusercontent.com/51853700/153345107-b6c46ec5-3876-4584-98f2-affcd6a98490.png)
![쏠라티-9-한달프로모션](https://user-images.githubusercontent.com/51853700/153345113-03689caa-6493-4d09-8930-0a914e2df9c3.png)
![쏠라티-10-고객센터](https://user-images.githubusercontent.com/51853700/153345114-50de5855-fd6c-4828-8961-7f5b0a5b84ad.png)
![쏠라티-11-Q A](https://user-images.githubusercontent.com/51853700/153345115-4cec993b-7ca1-4890-a07e-150dde7e6310.png)

**Comment by Jay-JYKim91** [comment]
솔라티 = 리무진

**Comment by sne12345** [comment]
![코치맨-0](https://user-images.githubusercontent.com/51853700/153364113-5e66ca53-c845-4762-ac89-ef492125a46d.png)
![코치맨-1](https://user-images.githubusercontent.com/51853700/153364114-f4a6b0a8-cd88-432c-9d2b-5d464e64d413.png)
![코치맨-2](https://user-images.githubusercontent.com/51853700/153364118-9035261d-b059-401d-bf4d-867b6ea0754f.png)
![코치맨-3-사진](https://user-images.githubusercontent.com/51853700/153364122-260d4e2c-ab0c-440b-bb4b-d77c4c2e6a90.png)
![코치맨-4-옵션-가격표x](https://user-images.githubusercontent.com/51853700/153364130-6c7f4e57-db33-4a98-86ac-eda6659ea898.png)
![코치맨-5](https://user-images.githubusercontent.com/51853700/153364132-b8d493c2-2fea-4bab-b471-4d2c9c52ec55.png)
![코치맨-6](https://user-images.githubusercontent.com/51853700/153364133-cd07290d-6443-4516-a0a4-f3c7c4f2aadf.png)
![코치맨-7-도면](https://user-images.githubusercontent.com/51853700/153364134-87366332-2eb3-4a73-a51d-5c55308768b2.png)
![코치맨-8](https://user-images.githubusercontent.com/51853700/153364137-18e1059e-0585-4599-94c3-1df60dbeceb2.png)
![코치맨-9-차고지](https://user-images.githubusercontent.com/51853700/153364140-3fef67f6-03d4-4cac-9f9c-2a10ade3774f.png)
![코치맨-10-고객센터](https://user-images.githubusercontent.com/51853700/153364146-9a050e77-8985-461d-abac-035a474774bd.png)
![코치맨-11-Q A](https://user-images.githubusercontent.com/51853700/153364110-c5ecc4dc-4082-4159-8ce2-d2f4e3b92142.png)

**Comment by sne12345** [comment]
# 캠핑카렌트 -> 보유차량 
### 세이브카의 깔끔한 호텔급 캠핑카로 
### 따뜻하고 안락한 캠핑을 즐겨보세요.

# 프로모션
### 통큰 할인혜택으로 합리적인 가격에
### 캠핑카를 이용해보세요.

# 세이브카 캠핑카의 장점
### 세이브카 캠핑카의 장점 6가지를 만나보세요.

**Comment by sne12345** [comment]
# @PostMapping(value="/admin/campingcar/mainText")
### 보내는 데이터

    private String carName;
    private int title;
    private String url;
    private String isUploaded;
    private MultipartFile file;

### 받는 데이터

    return "result" -> 1
