### ISSUE TITLE
월+12/24개월렌트 상세페이지

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#225]
# (모바일)사진 아래에 추가 / (PC) 사진 오른쪽에 추가
![image](https://user-images.githubusercontent.com/51853700/156090933-ce9c2d6f-6d06-42c9-80b6-35e2d64b868d.png)

**Comment by sne12345** [comment]
* 리뷰랑 필독사항은 X

**Comment by Jay-JYKim91** [comment]
차량정보에 차량번호 넣기

부가서비스에 차량배달 옆에 배달비 모달
아래 표에 보증금 넣기
