### ISSUE TITLE
관리자 페이지 등록 디자인 수정 

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#290]
![image](https://user-images.githubusercontent.com/51853700/159885469-16885745-d585-4d62-a71c-5c5e0263e757.png)
![image](https://user-images.githubusercontent.com/51853700/159886089-be111c13-5680-48ae-a0ba-36670dbf7cec.png)

**Comment by sne12345** [comment]
![image](https://user-images.githubusercontent.com/51853700/159885909-67ea2560-94e7-4d48-84a2-330b2b2f2972.png)

**Comment by Jay-JYKim91** [comment]
캠핑카 > 예약 등록, 예약현황 중 디테일 페이지
렌트카 > 가격 등록
누구나장기렌트 > 차량 등록

상담신청내역 > 디테일 페이지


현재 대여가능차량 예약 내역 > 디테일 페이지
