### ISSUE TITLE
할인가 오류수정

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#43]
* 모바일로 봤을 때 빨간줄 안 그어짐
* 약정주행거리 기타 선택하면 오류남
* 3일 이내 입고예정차량에도 적용이 되는지?
* 수정하기에서 null값 입력했을 때(아무것도 입력하지 않았을 때), null값이 아닌 기존 할인퍼센트 그대로 남도록 처리하기
* 할인가 추가/수정/삭제 시, result 값을 0으로 보낸거 alert 처리 ex)추가시, 이미 등록된 차량입니다. 수정시, 아직 등록되지 않은 차량입니다. 등등

**Comment by Jay-JYKim91** [comment]
- [왜 때문인지 아직 모르겠음, 구글링 중] 모바일로 봤을 때 빨간줄 안 그어짐
- [완료] 약정주행거리 기타 선택하면 오류남
- [적용됨] 3일 이내 입고예정차량에도 적용이 되는지?
- [완료] 수정하기에서 null값 입력했을 때(아무것도 입력하지 않았을 때), null값이 아닌 기존 할인퍼센트 그대로 남도록 처리하기
- [ ] 할인가 추가/수정/삭제 시, result 값을 0으로 보낸거 alert 처리 ex)추가시, 이미 등록된 차량입니다. 수정시, 아직 등록되지 않은 차량입니다. 등등

**Comment by sne12345** [comment]
수정완료
