### ISSUE TITLE
이 부분은 어떤 목적으로 사용한 코드인가요??

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#54]
![image](https://user-images.githubusercontent.com/51853700/140449757-31cdfa8f-58d5-41ee-9c1b-03554cefaddf.png)

**Comment by Jay-JYKim91** [comment]
이거 이미 할인 적용 되어 있는 거를 또 할인 적용할라고 하면 '이미 할인 적용됨'이 뜨고 나머지는 정상적으로 처리할려고 넣은거예요
