### ISSUE TITLE
[중요] 모렌 예약 프로세스 중 수정사항

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#89]
# 1. 결제폼
### 이렇게 변경
![image](https://user-images.githubusercontent.com/51853700/141606372-fddb9254-6dc7-4667-bb6e-1f269983c4b6.png)

### 디자인 참고
![image](https://user-images.githubusercontent.com/51853700/141603598-d9873ac8-34d8-460d-baf1-96e7f3452c58.png)

# 2. 대여날짜
![image](https://user-images.githubusercontent.com/51853700/141603790-76179cee-97cb-4b1c-ac87-2520dad6c587.png)
### + 디자인 아래와 같이 변경하기 / 누르면 기본 달력이랑 시간 나오는것은 동일 / 아이콘도 변경
![image](https://user-images.githubusercontent.com/51853700/141606190-38a83937-1595-4d9f-9f93-542451e464a7.png)

# 3. 예약신청하기 했을 때 alert 내용 변경하기
### 예약을 완료하시겠습니까? -> 예약 신청을 완료하시겠습니까?
<br /> 

![image](https://user-images.githubusercontent.com/51853700/141606072-eea3e1d0-a535-4d50-ac81-9debf0b9a080.png)

# 4. 디자인 수정
### 주소 검색버튼 더 크고 선명하게, 글자색 검은색으로
![image](https://user-images.githubusercontent.com/51853700/141606289-0c62e5a8-746a-4a19-951a-11287d13d572.png)

# 5. 차량정보 탭 추가
![image](https://user-images.githubusercontent.com/51853700/141607574-79244a80-fdb0-4cab-a883-b9c99acc8e0a.png)

# 6. 계좌번호 디자인
### 아래와 같이 변경
![image](https://user-images.githubusercontent.com/51853700/141610034-3e2b7468-9b0a-4930-8159-542ea78faa14.png)

# 7. 레이아웃
### 왼쪽 오른쪽 바꾸기 / 모바일에서는 위 아래 바뀜 
![image](https://user-images.githubusercontent.com/51853700/141610893-585ea43e-71ee-48fb-b3c5-c1de626dea17.png)

# 8. 레이아웃 수정
### 모바일에서 아래 박스가 맨 위로 가도록 
![image](https://user-images.githubusercontent.com/51853700/141762293-bc8e3839-78d5-4567-994e-da4c50922822.png)

# [아직 하지마세요] 예약 날짜 시간 변경시 위약금

### 디자인
![image](https://user-images.githubusercontent.com/51853700/141607600-15ac6d87-6f91-412e-b6fe-479810e04f7a.png)
****

**Comment by Jay-JYKim91** [comment]
credit에 보증금 30프로 하면 보증금: 차량가격의 30%(상담문의) 로 표기
모렌으로 보낼 때 보증금에 상담일때만 0
