### ISSUE TITLE
모렌으로 추가데이터 보내기 

### ISSUE THREAD

**Issue by sne12345** [SAVE-CAR/Rentcar-Website-SpringBoot#93]
private String carNo;      // 차량번호
    private String kilometer;  // 약정주행거리
    private String reservationName;   // 예약자 이름(입금자명)
    private String reservationPhone;  // 예약자 전화번호
    private String reservationAge;    // 예약자 만 나이
    private String reservationDate;   // 예약 날짜
    private String reservationTime;   // 예약 시간
    private String reservationGuarantee;   // 신용카드보유 or 소득증빙
    private String reservationDetails;     // 요청사항
    private String address;                // 배차요청 주소
    private String addressDetail;          // 배차요청 상세주소
    private String carPrice;               // 렌트료
    private String carTax;                 // 부가세
    private String carAmountTotal;         // 총렌트료
    private String carDeposit;             // 보증금

**Comment by Jay-JYKim91** [comment]
개런티를 reservation details에 , 신용보증: 개런티 내용 으로
아이디 그냥 두고, 그럼 위에 총 16개 데이터

**Comment by Jay-JYKim91** [comment]
보내는 데이터
- carNo
- kilometer
- reservationName
- reservationPhone
- reservationAge
- reservationDate
- reservationTime
- reservationDetails // 게런티 내용 포함
- address
- addressDetail
- carPrice
- carTax
- carAmountTotal
- carDeposit
- id
